### ISSUE TITLE
Sample wavetable

### ISSUE THREAD

**Issue by antoniograzioli** [av500/vcvrackplugins_av500#1]
Really Coooool
How did you create the wavetable for the Cowbell ???

**Comment by av500** [comment]
there are 808 samples out there on the internet :)

**Comment by antoniograzioli** [comment]
I know but how do you convert them in to wavetable?

**Comment by av500** [comment]
I used Audacity, saved them as raw PCM samples then used xxd -i on the command line to produce a C header

**Comment by antoniograzioli** [comment]
ok many many thanks

**Comment by av500** [comment]
you're welcome :)
