### ISSUE TITLE
Plugins don't load in fresh build of VCV Rack

### ISSUE THREAD

**Issue by oblivionratula** [av500/vcvrackplugins_av500#2]
Don't know if this is better here or the main VCV project, but I compiled your plugins in the plugins directory, but they don't load in VCV Rack.  Any leads?  On Mac:

`Failed to read init() symbol in /Users/*me*/Rack/plugins/vcvrackplugins_av500/plugin.dylib`

Thanks.

**Comment by av500** [comment]
yes, the problem is that the plugin pack is called just "av500" but my git repo is called "vcvrackplugins_av500" - so just rename the folder to "av500" and it should work

**Comment by oblivionratula** [comment]
No dice. Same error.

**Comment by av500** [comment]
do you have the file /Users/*me*/Rack/plugins/av500/plugin.dylib at all? did you type "make" in the plugins/av500 folder?

**Comment by av500** [comment]
ah sorry, the path name issue would only show in blank panels, but the plugin would still load, it's something else then

**Comment by oblivionratula** [comment]
Indeed, make seemed to succeed. 

`-rwxr-xr-x  1 me  staff  280108 Sep 27 09:20 plugin.dylib`

**Comment by av500** [comment]
hmm, no idea then. I did a Linux build, I'll try on the office Mac tomorrow...

**Comment by oblivionratula** [comment]
Ah, FWIW, it DOES work in my linux VM. The p0wr module is cute. ;)

Would still like to get it running on Mac if possible.  No rush, though. Thanks.

**Comment by oblivionratula** [comment]
I have no idea what I'm doing - a complete hack - but I got it to work by modeling the src/av500.cpp file after the Fundamental.cpp.  Thus:

```
#include "av500.hpp"

Plugin *plugin;

void init(rack::Plugin *p) {
                plugin = p;
                plugin->slug = "av500";
                plugin->name = "av500";
                createModel<MultipleWidget>  (plugin, "av500 Multiple",         "Triple Multiple");
                createModel<Blank8hpWidget>  (plugin, "av500 8hp Blank",        "8hp Blank");
                createModel<p0wrWidget>      (plugin, "av500 p0wr",     "p0wr");
                createModel<TR808CowbellWidget>(plugin, "av500 808Cowbell", "808Cowbell");
        }

``` 

The modules load and the mult does what a mult should.  The Cowbell panel is blank, however. 

Were there changes in the plugin structuring maybe?

**Comment by av500** [comment]
ok, I see. I think its due to the fact that the vcv code has changed and I have not updated my plugin code for that. let me do that tonight

**Comment by av500** [comment]
ok, it should work now, thanks for pointing out the changes :)  the missing cowbell panel is most likely due to some path not OK, do you have plugins/av500 as the path?

**Comment by oblivionratula** [comment]
I misspoke. Cowbell has a panel.  Says CowBell, has an input and output jack, and works. Just no knobs.  This may be intentional.

**Comment by oblivionratula** [comment]
And I can confirm a fresh pull and make with the changes works on Mac.  Thanks. The mult is so simple, but so needed. ;)

**Comment by av500** [comment]
the original 808 cowbell has no parameters or knobs, so this module only plays a sample of it :)

**Comment by oblivionratula** [comment]
Then it's perfect!  
And very modular.
;)
