### ISSUE TITLE
Make issue with v.04.0

### ISSUE THREAD

**Issue by ortenheim** [av500/vcvrackplugins_av500#4]
Mac osx, sierra.
`
 /Applications/Rack/plugins/av500   master  make
c++ -fshort-enums -DTEST -I./eurorack -Wno-unused-local-typedefs -fPIC -I../../include -I../../dep/include -DVERSION=dev -DVERSION_dev -MMD -O3 -march=nocona -ffast-math -Wall -g -DARCH_MAC -mmacosx-version-min=10.7 -std=c++11 -stdlib=libc++ -c -o build/src/TR808Cowbell.cpp.o src/TR808Cowbell.cpp
src/TR808Cowbell.cpp:17:2: error: unknown type name 'SchmittTrigger'
        SchmittTrigger trigger;
        ^
src/TR808Cowbell.cpp:50:12: error: cannot initialize a parameter of type
      'rack::Module *' with an lvalue of type 'TR808Cowbell *'
        setModule(module);
                  ^~~~~~
../../include/app.hpp:37:25: note: passing argument to parameter 'module' here
        void setModule(Module *module);
                               ^
src/TR808Cowbell.cpp:63:12: error: no matching function for call to 'createInput'
        addInput (createInput <PJ3410Port>(Vec( 0, 300), module, TR808Cowbell:...
                  ^~~~~~~~~~~~~~~~~~~~~~~~
../../include/rack.hpp:52:7: note: candidate function [with TPort = rack::PJ3410Port]
      not viable: no known conversion from 'TR808Cowbell *' to 'rack::Module *' for
      2nd argument
Port *createInput(Vec pos, Module *module, int inputId) {
      ^
src/TR808Cowbell.cpp:64:12: error: no matching function for call to 'createOutput'
        addOutput(createOutput<PJ3410Port>(Vec(30, 300), module, TR808Cowbell:...
                  ^~~~~~~~~~~~~~~~~~~~~~~~
../../include/rack.hpp:62:7: note: candidate function [with TPort = rack::PJ3410Port]
      not viable: no known conversion from 'TR808Cowbell *' to 'rack::Module *' for
      2nd argument
Port *createOutput(Vec pos, Module *module, int outputId) {
      ^
4 errors generated.
make: *** [build/src/TR808Cowbell.cpp.o] Error 1`

**Comment by av500** [comment]
fixed by 110ac0294101a29bd0906cf9a3cf8627322da5a5
