### ISSUE TITLE
808 cowbell not loading

### ISSUE THREAD

**Issue by retop56** [av500/vcvrackplugins_av500#6]
When I try to load a patch that uses the 808Cowbell module I get an error that reads: "Could not find plugin "av500" for module "av500 808Cowbell". The path for your plugin folder I used is "C:\Users\my_username\Desktop\Rack\plugins\av500". How do I fix this? Thanks.

**Comment by av500** [comment]
there was an issue to compile av500 plugins that I just fixed, it should build again now
